
[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "ComicMono NF"
# style = "Bold"

[font.bold_italic]
family = "MonaspiceRn Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MonaspiceRn Nerd Font Mono"
style = "Italic"

[font.normal]
family = "ComicMono NF"
# style = "Regular"

[window]
dimensions = { columns = 96, lines = 26 }

padding = { x = 0, y = 0 }

dynamic_padding = false

decorations = "Full"

opacity = 0.7

blur = true

startup_mode = "Windowed"

dynamic_title = true

class = { instance = "Alacritty", general = "Alacritty" }

decorations_theme_variant = "None"

resize_increments = false

option_as_alt = "None"

[general]
#Import
import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]
