[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
# family = "ComicMono NF"
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
# family = "ComicMono NF"
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"


[window]
dimensions = { columns = 0, lines = 0 }

padding = { x = 10, y = 10 }

dynamic_padding = true

decorations = "None"

opacity = 0.7

blur = true

startup_mode = "Windowed"

dynamic_title = true

class = { instance = "Alacritty", general = "Alacritty" }

decorations_theme_variant = "None"

resize_increments = false

option_as_alt = "None"

[general]
#Import
import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]
