#!/usr/bin/bash

socat -u "UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - |
  while read -r line; do
    if [[ $line == activewindow* ]]; then
      hyprctl -j activewindow | jq .title
    fi
  done &
hyprctl -j activewindow | jq .title
wait
