[manager]
prepend_keymap = [
    { on = "J", run = "arrow 5", desc = "Move cursor 5 lines down" },
    { on = "K", run = "arrow -5", desc = "Move cursor 5 lines up" },
    { on = "T", run = "plugin --sync max-preview", desc = "Maximize or restore preview" },
    { on = [
        "c",
        "m",
    ], run = "plugin chmod", desc = "Chmod on selected files" },
]
append_keymap = [
    { on = "<C-j>", run = "seek 5", desc = "Seek down 5 units in the preview" },
    { on = "<C-k>", run = "seek -5", desc = "Seek down -5 units in the preview" },
    { on = ["g","w"], run = "cd ~/Workspaces", desc = "Go to Workspaces" },
]
