[mgr]
prepend_keymap = [
    { on = "J", run = "arrow 5", desc = "Move cursor 5 lines down" },
    { on = "K", run = "arrow -5", desc = "Move cursor 5 lines up" },
    { on = "T", run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },
    { on = [
        "c",
        "m",
    ], run = "plugin chmod", desc = "Chmod on selected files" },
	{ on = [ "g", "i" ], run = "plugin lazygit", desc = "run lazygit" },
	{ on = [ "c", "a" ], run = "plugin compress", desc = "Archive selected files" },
	{ on = "M", run = "plugin mount", desc = "mount disk"},
	{ on = "!", for = "unix", run = 'shell "$SHELL" --block', desc = "Open $SHELL here" },
]
append_keymap = [
    { on = "<C-j>", run = "seek 5", desc = "Seek down 5 units in the preview" },
    { on = "<C-k>", run = "seek -5", desc = "Seek down -5 units in the preview" },
    { on = ["g","w"], run = "cd ~/Workspaces", desc = "Go to Workspaces" },
]

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"
