[opener]
edit = [
    { run = 'lvim "$@"', block = true },
    { run = 'nvim "$@"', block = true },
    { run = 'vim "$@"', block = true },
    { run = 'helix "$@"', block = true },
    { run = 'neovide "$@"', block = true},
]
play = [
    { run = 'mpv "$@"', orphan = true, for = "unix" },
    { run = 'vlc "$@"', orphan = true, for = "unix" },
]
open = [
    { run = 'xdg-open "$@"', desc = "Open" }
]

[preview]
# Change them to your desired values
max_width  = 10000
max_height = 10000
