[opener]
edit = [
    { run = 'nvim "$@"', block = true },
    { run = 'lvim "$@"', block = true },
	{ run = 'helix "$@"', block = true },
    { run = 'neovide "$@"', block = true},
]
play = [
    { run = 'mpv "$@"', orphan = true, for = "unix" },
    { run = 'vlc "$@"', orphan = true, for = "unix" },
]
open = [
    { run = 'nvim "$@"', block = true },
    { run = 'xdg-open "$@"', desc = "Open" }
]

[preview]
# Change them to your desired values
max_width  = 10000
max_height = 10000

[plugin]
# use magick to preview svg
  prepend_preloaders = [
    { mime = "image/svg+xml", run = "magick" },
  ]
  prepend_previewers = [
    { mime = "image/svg+xml", run = "magick"},
  ]

