[mgr]
sort_by = "natural"
sort_dir_first = true
linemode = "size"

[preview]
max_width = 1000
max_height = 1000
image_quality = 50

[opener]
edit = [
  { run = 'nvim "$@"', block = true },
  { run = 'helix "$@"', block = true },
  { run = 'neovide "$@"', block = true },
  { run = 'lvim "$@"', block = true },
]
play = [{ run = 'mpv "$@"', orphan = true, for = "unix" }]
open = [
  { run = 'xdg-open "$@"', desc = "XDG-Open" },
  { run = 'nvim "$@"', block = true },
]

[tasks]
micro_workers = 10
macro_workers = 10

[plugin]
# use magick to preview svg
prepend_preloaders = [
  { mime = "image/svg+xml", run = "magick" },
  { mime = "application/pdf", run = "noop" },
  # { mime = "video/*", run = "noop" },
  { name = "/media/**", run = "noop" },
]
prepend_previewers = [
  { mime = "image/svg+xml", run = "magick" },
  { mime = "application/pdf", run = "noop" },
  { name = "/media/**", run = "noop" },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
