theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
cursorline = true
completion-trigger-len = 1
bufferline = "always"
idle-timeout = 0
color-modes = true

[editor.statusline]
left = ["mode", "spacer", "version-control", "file-name", "spinner", "diagnostics"]
right = ["position", "primary-selection-length", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal]
J = ["move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down"]
K = ["move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up"]
